name: "Validation And Formatting"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  test:
    runs-on: "ubuntu-latest"
    name: PyTest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4"

      - name: Setup Python
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: "pip install -r requirements.txt"

      - name: Run tests
        run: "pytest --doctest-modules --junitxml=junit/test-results.xml --cov=custom_components --cov-report=xml --cov-report=html tests"
